#!/usr/bin/env ruby


require File.expand_path(File.dirname(__FILE__) + "/config")
require "rindlets/stock_source_rindlet"
 
p ARGV
stock = ARGV[0]
puts "Starting #{stock}"
StockSourceRindlet.new(stock).start
